import type { TFunction } from "i18next";
interface Package {
  packageId: string;
  packageName: string;
  returnPercentage: string;
  description: string;
  minimumInvestment: string;
  duration: string;
  riskLevel: string;
  variant?: 'light' | 'dark';
}
 export const getUsdPackages = (t: TFunction): Package[] => [
    {
      packageId: "8",
      packageName: t('packages.starter.name'),
      returnPercentage: "3%",
      description: t('packages.starter.description'),
      minimumInvestment: "$1,000",
      duration: t('packages.starter.duration'),
      riskLevel: t('packages.starter.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "9",
      packageName: t('packages.growth.name'),
      returnPercentage: "4%",
      description: t('packages.growth.description'),
      minimumInvestment: "$4,000",
      duration: t('packages.growth.duration'),
      riskLevel: t('packages.growth.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "1",
      packageName: t('packages.premium.name'),
      returnPercentage: "5%",
      description: t('packages.premium.description'),
      minimumInvestment: "$7,000",
      duration: t('packages.premium.duration'),
      riskLevel: t('packages.premium.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "2",
      packageName: t('packages.elite.name'),
      returnPercentage: "6%",
      description: t('packages.elite.description'),
      minimumInvestment: "$11,000",
      duration: t('packages.elite.duration'),
      riskLevel: t('packages.elite.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "3",
      packageName: t('packages.flexi.name'),
      returnPercentage: "7%",
      description: t('packages.flexi.description'),
      minimumInvestment: "$15,000",
      duration: t('packages.flexi.duration'),
      riskLevel: t('packages.flexi.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "4",
      packageName: t('packages.visionary.name'),
      returnPercentage: "9%",
      description: t('packages.visionary.description'),
      minimumInvestment: "$21,000",
      duration: t('packages.visionary.duration'),
      riskLevel: t('packages.visionary.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "5",
      packageName: t('packages.legendary.name'),
      returnPercentage: "10%",
      description: t('packages.legendary.description'),
      minimumInvestment: "$31,000",
      duration: t('packages.legendary.duration'),
      riskLevel: t('packages.legendary.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "6",
      packageName: t('packages.infinity.name'),
      returnPercentage: "12%",
      description: t('packages.infinity.description'),
      minimumInvestment: "$110,000",
      duration: t('packages.infinity.duration'),
      riskLevel: t('packages.infinity.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "7",
      packageName: t('packages.supreme.name'),
      returnPercentage: "13%",
      description: t('packages.supreme.description'),
      minimumInvestment: "$200,000",
      duration: t('packages.supreme.duration'),
      riskLevel: t('packages.supreme.paymentFrequency'),
      variant: "dark" as const,
    },
  ];

  // EGP Packages (IDs 10-14)
 export const egpPackages = (t: TFunction): Package[] => [
    {
      packageId: "10",
      packageName: t('packages.silver.name'),
      returnPercentage: "4%",
      description: t('packages.silver.description'),
      minimumInvestment: "15,000 EGP",
      duration: t('packages.silver.duration'),
      riskLevel: t('packages.silver.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "11",
      packageName: t('packages.gold.name'),
      returnPercentage: "5%",
      description: t('packages.gold.description'),
      minimumInvestment: "60,000 EGP",
      duration: t('packages.gold.duration'),
      riskLevel: t('packages.gold.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "12",
      packageName: t('packages.platinum.name'),
      returnPercentage: "6%",
      description: t('packages.platinum.description'),
      minimumInvestment: "160,000 EGP",
      duration: t('packages.platinum.duration'),
      riskLevel: t('packages.platinum.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "13",
      packageName: t('packages.diamond.name'),
      returnPercentage: "8%",
      description: t('packages.diamond.description'),
      minimumInvestment: "310,000 EGP",
      duration: t('packages.diamond.duration'),
      riskLevel: t('packages.diamond.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "14",
      packageName: t('packages.honestEgy.name'),
      returnPercentage: "10%",
      description: t('packages.honestEgy.description'),
      minimumInvestment: "620,000 EGP",
      duration: t('packages.honestEgy.duration'),
      riskLevel: t('packages.honestEgy.paymentFrequency'),
      variant: "dark" as const,
    },
    {
      packageId: "15",
      packageName: t('packages.honestEgyplus.name'),
      returnPercentage: "13%",
      description: t('packages.honestEgyplus.description'),
      minimumInvestment: "1,000,000 EGP",
      duration: t('packages.honestEgyplus.duration'),
      riskLevel: t('packages.honestEgyplus.paymentFrequency'),
      variant: "dark" as const,
    },
  ];

  export const getHHpacks = (t: TFunction): Package[] => [
  {
    packageId: "16",
    packageName: "Primary",
    returnPercentage: "10%",
    description: t('packages.primaryHH.description'),
    minimumInvestment: "750,000 EGP",
    duration:t('packages.primaryHH.duration'),
    riskLevel: t('packages.primaryHH.paymentFrequency'),
    variant: "dark" as const,
  },
  {
    packageId: "17",
    packageName: "Plus ",
    returnPercentage: "10%",
    description: t('packages.plusHH.description'),
    minimumInvestment: "1,000,000 EGP",
    duration:t('packages.plusHH.duration'),
    riskLevel: t('packages.plusHH.paymentFrequency'),

  },
  {
    packageId: "18",
    packageName: "Premium ",
    returnPercentage: "10%",
    description: t('packages.primaryHH.description'),
    minimumInvestment: "2,000,000 EGP",
    duration:t('packages.premiumHH.duration'),
    riskLevel: t('packages.premiumHH.paymentFrequency'),
    variant: "dark" as const,
  },
];
//   const investmentPackages = [
//     {packageId: "8",
//       packageName: t('packages.starter.name'),
//       returnPercentage: "3%",
//       description: t('packages.starter.description'),
//       minimumInvestment: "$1000",
//       duration: t('packages.starter.duration'),
//       riskLevel: t('packages.starter.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "9",
//       packageName: t('packages.growth.name'),
//       returnPercentage: "4%",
//       description: t('packages.growth.description'),
//       minimumInvestment: "$4000",
//       duration: t('packages.growth.duration'),
//       riskLevel: t('packages.growth.paymentFrequency'),
//       variant: "dark" as const,
//     },{
//       packageId: "1",
//       packageName: t('packages.premium.name'),
//       returnPercentage: "5%",
//       description: t('packages.premium.description'),
//       minimumInvestment: "$7000",
//       duration: t('packages.premium.duration'),
//       riskLevel: t('packages.premium.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "2",
//       packageName: t('packages.elite.name'),
//       returnPercentage: "6%",
//       description: t('packages.elite.description'),
//       minimumInvestment: "$11,000",
//       duration: t('packages.elite.duration'),
//       riskLevel: t('packages.elite.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "3",
//       packageName: t('packages.flexi.name'),
//       returnPercentage: "7%",
//       description: t('packages.flexi.description'),
//       minimumInvestment: "$15,000",
//       duration: t('packages.flexi.duration'),
//       riskLevel: t('packages.flexi.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "4",
//       packageName: t('packages.visionary.name'),
//       returnPercentage: "9%",
//       description: t('packages.visionary.description'),
//       minimumInvestment: "$21,000",
//       duration: t('packages.visionary.duration'),
//       riskLevel: t('packages.visionary.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "5",
//       packageName: t('packages.legendary.name'),
//       returnPercentage: "10%",
//       description: t('packages.legendary.description'),
//       minimumInvestment: "$31,000",
//       duration: t('packages.legendary.duration'),
//       riskLevel: t('packages.legendary.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "6",
//       packageName: t('packages.infinity.name'),
//       returnPercentage: "12%",
//       description: t('packages.infinity.description'),
//       minimumInvestment: "$110,000",
//       duration: t('packages.infinity.duration'),
//       riskLevel: t('packages.infinity.paymentFrequency'),
//       variant: "dark" as const,
//     },
//     {
//       packageId: "7",
//       packageName: t('packages.supreme.name'),
//       returnPercentage: "13%",
//       description: t('packages.supreme.description'),
//       minimumInvestment: "$200,000",
//       duration: t('packages.supreme.duration'),
//       riskLevel: t('packages.supreme.paymentFrequency'),
//       variant: "dark" as const,
//     },   
//     {
//     packageId: "10",
//     packageName: t('packages.silver.name'),
//     returnPercentage: "4%",
//     description: t('packages.silver.description'),
//     minimumInvestment: "15,000 EGP",
//     duration: t('packages.silver.duration'),
//     riskLevel: t('packages.silver.paymentFrequency'),
//     variant: "dark" as const,
//   },
//   {
//     packageId: "11",
//     packageName: t('packages.gold.name'),
//     returnPercentage: "5%",
//     description: t('packages.gold.description'),
//     minimumInvestment: "60,000 EGP",
//     duration: t('packages.gold.duration'),
//     riskLevel: t('packages.gold.paymentFrequency'),
//     variant: "dark" as const,
//   },
//   {
//     packageId: "12",
//     packageName: t('packages.platinum.name'),
//     returnPercentage: "6%",
//     description: t('packages.platinum.description'),
//     minimumInvestment: "160,000 EGP",
//     duration: t('packages.platinum.duration'),
//     riskLevel: t('packages.platinum.paymentFrequency'),
//     variant: "dark" as const,
//   },
//   {
//     packageId: "13",
//     packageName: t('packages.diamond.name'),
//     returnPercentage: "8%",
//     description: t('packages.diamond.description'),
//     minimumInvestment: "310,000 EGP",
//     duration: t('packages.diamond.duration'),
//     riskLevel: t('packages.diamond.paymentFrequency'),
//     variant: "dark" as const,
//   },
//   {
//     packageId: "14",
//     packageName: t('packages.honestEgy.name'),
//     returnPercentage: "10%",
//     description: t('packages.honestEgy.description'),
//     minimumInvestment: "620,000 EGP",
//     duration: t('packages.honestEgy.duration'),
//     riskLevel: t('packages.honestEgy.paymentFrequency'),
//     variant: "dark" as const,
//   },

//   ];